### ISSUE TITLE
Transfer repo?

### ISSUE THREAD

**Issue by technomancy** [redguardtoo/find-file-in-project#121]
Hey @redguardtoo you've been doing a lot of development on this; would you like me to transfer this repo to your account? I've been archiving repositories in my account that I'm not actively using, but this is still quite active. It doesn't seem like it belongs under my name any more. =)

**Comment by redguardtoo** [comment]
Sure. So Just need fork find-file-in-project, right?

**Comment by technomancy** [comment]
Cool; I requested a transfer so it should keep all the issues and discussion history and set up a redirect.

**Comment by technomancy** [comment]
I have tried three times to transfer the repository, but GitHub refuses to do anything about it. Maybe it could be resolved by contacting GitHub staff or something? I'm not sure what to do about it. It just says in the settings page "This repository is being transferred to @redguardtoo." which appears to be false.

**Comment by redguardtoo** [comment]
@technomancy , thanks for the heads up. I accept the transfer in email. should happen in one day.

**Comment by technomancy** [comment]
Looks like it went thru this time; cool.
