### ISSUE TITLE
A minor problem about function `ffip-create-project-file`

### ISSUE THREAD

**Issue by dalugm** [redguardtoo/find-file-in-project#124]
https://github.com/redguardtoo/find-file-in-project/blob/c4c7ec595c54c3006299717b1fd83e357864b2d5/find-file-in-project.el#L760

Should we add a space between the prompt string and the custom directory? And I think we should change `?` to `:`

Just like 

```elisp
(read-directory-name "Project root directory: " default-directory))
```

Otherwise, it is difficult to distinguish between the prompt string and the directory.

**Comment by redguardtoo** [comment]
11bc01e hint minor issue (Chen Bin)

**Comment by dalugm** [comment]
@redguardtoo  谢谢，顺祝除夕快乐，希望大佬在接下来的牛年里身体健康、事业进步！🧧
