### ISSUE TITLE
path completion no longer works in latest version

### ISSUE THREAD

**Issue by sonwh98** [redguardtoo/find-file-in-project#130]
M-x ffip use to show a list of files as I type. This is no longer the case in the latest version. I had to downgrade to 5.7.13

**Comment by redguardtoo** [comment]
Check README. ffip used to use ivy as default completion framework. Now we let use choose the completion framework. You can use ido/helm/ivy or any other modern completion framework.

**Comment by sonwh98** [comment]
Thank you. I think there should be reasonable defaults without having users to explicitly choose. Since ido comes with emacs by default, it should be the default.  (setq ffip-prefer-ido-mode t) should be the default

**Comment by redguardtoo** [comment]
@sonwh98 These days many people prefer modern completion framework like helm/ivy/selectrum/consult.

**Comment by evanbowman** [comment]
I appreciate your work on this project, but for longtime users of ffip who have been using this plugin for many years, it's annoying to have the behavior change without warning, then have to dig through the issue tracker to figure out what changed.

I disagree that users can simply enable ivy-mode to get the old behavior back. (ivy-mode 1) enables ivy globally.

**Comment by redguardtoo** [comment]
`ffip` support ido/ivy/helm and other completion frameworks. See its doc.
