### ISSUE TITLE
Raise warnings when accidentally execute this find-file-in-project in (real) big folder?

### ISSUE THREAD

**Issue by juniorxxue** [redguardtoo/find-file-in-project#132]
Thanks for your package.

I bind this command to a handy shortcut and sometimes will accidentally execute it in computer root directory.
then I have to force quit my emacs because it's frozen.

Could it raise some warnings when it detects the fact it's in a very large folder?

Best

**Comment by redguardtoo** [comment]
In Emacs, you can alway press `C-g` to quit any process.

**Comment by juniorxxue** [comment]
> you can alway press C-g to quit any process

Thanks!! I haven't even known yet.

> what commands I actually recommend

Sure, thought not my initial intention, but it's totally okay for me.
