### ISSUE TITLE
Would it be possible to prevent search in given folders 

### ISSUE THREAD

**Issue by avatar-lavventura** [redguardtoo/find-file-in-project#133]
Would it be possible to prevent search in given folders such as `.git`, `.mypy_cache/`

<img width="965" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/18537398/129033529-6fc83d3a-17a9-4b15-97b8-e88b0d3e499b.png">

For example I don't want to see find files under `.mypy_cache`, if possible.

**Comment by redguardtoo** [comment]
`ffip-prune-patterns`

**Comment by avatar-lavventura** [comment]
I have tried:

```
(defun my-setup-develop-environment ()
  (interactive)
  (add-to-list 'ffip-prune-patterns "*/.mypy_cache"))
```

but it did not help :(

**Comment by redguardtoo** [comment]
It works on my computer.

Please note `ffffip-prune-patterns` is buffler local variable. You need run this command in the buffer you will trigger ffip command.

Or you can set `ffip-prune-patterns` in major mode hook.

Or check README to how to set up it in `.dir-locals.el`

Or just `(setq-default ffip-prune-patterns (add-to-list 'ffip-prune-patterns "*/.mypy_cache"))` in your `~/.emacs`.

**Comment by redguardtoo** [comment]
```lisp
(with-eval-after-load 'find-file-in-project
  (setq-default ffip-prune-patterns (add-to-list 'ffip-prune-patterns "*/.mypy_cache")) )
```
