### ISSUE TITLE
How to suppress "stty: 'standard input': Inappropriate ioctl for device" message

### ISSUE THREAD

**Issue by avatar-lavventura** [redguardtoo/find-file-in-project#134]
When I apply `find-file-in-project` I keep seeing `stty: 'standard input': Inappropriate ioctl for device` warning message, would it be possible to suppress it?

```
520  Find in my_project/:
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device
```

**Comment by redguardtoo** [comment]
If you use `find-file-in-project-at-point` or `find-file-in-project-by-selected` as I recommend in README.  You won't see the noise at all. And it's much faster than `find-file-in-project` or `ffip`.

I also did a quick search of the error message. Looks you can set up your default shell to solve this problem

Or see my latest code, you can set `ffip-project-search-function`,

534ae8e make file search function configurable (Chen Bin)

**Comment by avatar-lavventura** [comment]
`find-file-in-project-at-point ` helped.

I have also make changes in my `.zshenv` file as follows:

```
if [[ $- == *i* ]] ; then
    stty eof undef
    stty sane
    stty erase "^H" intr "^C" eof "^D" susp "^Z" # kill "^U"
    stty -ixon
fi
```
