### ISSUE TITLE
Would it be possible to use `find-file-in-project` if Icicles(`icy-mode`) is enabled?

### ISSUE THREAD

**Issue by avatar-lavventura** [redguardtoo/find-file-in-project#135]
I was using `icicles`(https://www.emacswiki.org/emacs/Icicles) for `ido-find-file`: 

```
(add-to-list 'load-path "~/.emacs.d/lisp/icicles")
(require 'icicles)
(icy-mode 1)
(add-hook 'icicles-mode-hook (lambda ()
                                (local-set-key (kbd "C-p") 'nil)))
(setq icicle-Completions-text-scale-decrease 0.00)
```

But when I use it `find-file-in-project` does not respond back to any entered words and halts. 

Would it be possible to use `find-file-in-project` if `icy-mode` is enabled?

**Comment by redguardtoo** [comment]
I'm not sure how can `icicles` be integrated. I only use ido api `ido-completing-read`. You can use `ido-vertical-mode` to improve ido's UI. But I don't use ido any more.
