### ISSUE TITLE
Regression in ffip-test-relative-path-commands from 6.0.7 to 1d2f0b3

### ISSUE THREAD

**Issue by sten0** [redguardtoo/find-file-in-project#139]
Sorry it took me so long to forward this issue.  1d2f0b3 has been ready to upload to Debian for a while, but is still blocked by this.  Logs attached.

[find-file-in-project_6.0.7-1_amd64.txt](https://github.com/redguardtoo/find-file-in-project/files/7834872/find-file-in-project_6.0.7-1_amd64.txt)
[find-file-in-project_6.1.2+2.g1d2f0b3-1_amd64.txt](https://github.com/redguardtoo/find-file-in-project/files/7834873/find-file-in-project_6.1.2%2B2.g1d2f0b3-1_amd64.txt)
.

**Comment by redguardtoo** [comment]
a62eaa0 try to fix test for debian (Chen Bin)

**Comment by sten0** [comment]
Thank you for the quick reply!  I wish the fix were so easy ;-)  If the test didn't pass previously then it wouldn't be a regression, and I wouldn't be concerned (yes, Debian CI does a fair amount of fuzzing).  Do you remember what commit might have changed the behaviour?  If it's truly a Debian-specific issue, then I can try 1. Checking for an envvar, 2. setting up a test project in $TMP or $TMPDIR, and 3. running the tests from there (assuming they're relocatable)

**Comment by redguardtoo** [comment]
`get-full-path` tries to return the full path of `git-diff.diff`. It assumes the parameter is the relative path of `ffip-tests.el`. It uses `load-file-name` but looks in debian, `load-file-name` is a bit different.

**Comment by sten0** [comment]
`load-file-name` isn't different in Debian; the regression was detected by some basic [fuzzing](https://en.wikipedia.org/wiki/Fuzzing) in our CI.  It's not 5060761, because `ffip-test-relative-path-commands` in 6.0.7 is good, and this is why this is a regression.

**Comment by sten0** [comment]
(I'm bisecting now)

**Comment by sten0** [comment]
`ffip-test-relative-path-commands` passes in 6.1.2, but fails in 52274e6, but the removal of `ert-deftest ffip-test-git-commands` should be irrelevant, which suggests the problem is elsewhere; this might take a while...

**Comment by sten0** [comment]
I couldn't find the problem, but the good news is the regression is fixed in 6.2.0!  Thank you :-)
